(() => {
  "use strict";
  const CONFIG = window.CHERRIFT_SUPABASE_CONFIG || {};
  const factory = window.supabase?.createClient;
  const $ = (id) => document.getElementById(id);
  const qa = (selector, root = document) => Array.from(root.querySelectorAll(selector));
  const state = { client:null, session:null, admin:null, account:null, catalog:[], mailTarget:null, profileTarget:null, profileOriginal:null, profileResourceOriginal:{}, profileGmTitlesOriginal:[], toastTimer:0 };
  const CATEGORY_LABELS = { currency:"Pénznemek", key:"Kulcsok", chest:"Ládák", material:"Materialok", bag_item:"Bag itemek" };
  const GM_TITLE_IDS = Object.freeze(["gm","senior_gm","head_gm"]);

  const escapeHtml = (value) => String(value ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
  function toast(message,error=false){const el=$("toast");el.textContent=String(message||"");el.classList.toggle("error",!!error);el.classList.add("show");clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.remove("show"),3600)}
  function setBusy(button,busy,text="Folyamatban…"){if(!button)return;if(busy){button.dataset.originalText=button.textContent;button.textContent=text;button.disabled=true}else{button.textContent=button.dataset.originalText||button.textContent;button.disabled=false}}
  async function copyText(value){const text=String(value||"");if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else{const a=document.createElement("textarea");a.value=text;a.style.position="fixed";a.style.opacity="0";document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}toast("Vágólapra másolva.")}
  function cleanRedirectUrl(){const url=new URL(location.href);for(const key of ["code","error","error_code","error_description"])url.searchParams.delete(key);url.hash="";return url.toString()}
  async function api(action,payload={}){if(!state.client)throw new Error("Supabase kliens nem érhető el.");const {data,error}=await state.client.functions.invoke("gm-api",{body:{action,...payload}});if(error){let detail=data?.error||error.message||"Edge Function hiba";if(error.context instanceof Response){try{const parsed=await error.context.clone().json();detail=parsed?.error||detail}catch(_){}}throw new Error(detail)}if(data?.error)throw new Error(data.error);return data}
  const accountLabel=(p)=>p?.name||p?.username||p?.discordId||p?.id||"Ismeretlen játékos";
  const listFromText=(value)=>[...new Set(String(value||"").split(/[\n,]+/).map(x=>x.trim()).filter(Boolean))];
  function avatarMarkup(p){return p?.avatar?`<img class="result-avatar" src="${escapeHtml(p.avatar)}" alt="">`:`<span class="result-avatar"></span>`}
  function formatDate(value){if(!value)return"—";const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleString("hu-HU"):"—"}
  function localDateToIso(id){const value=$(id)?.value;return value?new Date(value).toISOString():null}
  function showAuthStatus(text){$("authStatus").textContent=text}
  function showUnauthorized(userId,account){$("unauthorizedBox").classList.remove("hidden");$("unauthorizedUserId").textContent=userId||"";showAuthStatus(`${accountLabel(account)} be van jelentkezve, de nincs GM-joga.`)}

  function showApp(data){state.admin=data.admin;state.account=data.account;$("authView").classList.add("hidden");$("gmApp").classList.remove("hidden");$("adminName").textContent=accountLabel(data.account);$("adminRole").textContent=String(data.admin.role||"GM").toUpperCase();$("accountSheetName").textContent=accountLabel(data.account);$("accountSheetId").textContent=data.account.id||"";const avatar=$("adminAvatar");if(data.account.avatar){avatar.src=data.account.avatar;avatar.hidden=false;$("adminAvatarFallback").hidden=true}renderAllResourceBuilders();refreshMailHistory();refreshRedeemHistory()}
  async function resolveSession(){showAuthStatus("Discord munkamenet ellenőrzése…");const {data,error}=await state.client.auth.getSession();if(error)throw error;state.session=data.session;if(!state.session){showAuthStatus("Jelentkezz be a saját Discord-fiókoddal.");$("discordLoginBtn").disabled=false;return}showAuthStatus("GM-jogosultság ellenőrzése…");try{const me=await api("me");const catalog=await api("reward_catalog");state.catalog=Array.isArray(catalog.resources)?catalog.resources:[];showApp(me)}catch(error){const message=String(error?.message||error||"");if(message.includes("not_an_active_gm")){const user=state.session.user;showUnauthorized(user?.id,{id:user?.id,name:user?.user_metadata?.full_name||user?.user_metadata?.name,username:user?.user_metadata?.user_name})}else{showAuthStatus(`A gm-api nem érhető el: ${message}`);toast(message,true)}}}
  async function login(){const button=$("discordLoginBtn");setBusy(button,true,"Átirányítás…");const {error}=await state.client.auth.signInWithOAuth({provider:"discord",options:{redirectTo:cleanRedirectUrl()}});if(error){setBusy(button,false);toast(error.message,true)}}
  async function logout(){await state.client?.auth.signOut({scope:"local"});location.replace(cleanRedirectUrl())}
  function activateModule(name){qa("[data-module-view]").forEach(s=>s.classList.toggle("active",s.dataset.moduleView===name));qa("[data-module]").forEach(b=>b.classList.toggle("active",b.dataset.module===name));$("accountSheet").classList.add("hidden");scrollTo({top:0,behavior:"smooth"});if(name==="profiles")refreshActivity()}

  function groupCatalog(){const map=new Map();for(const row of state.catalog){if(!map.has(row.category))map.set(row.category,[]);map.get(row.category).push(row)}return map}
  function resourceInput(row,prefix,profile=false){const icon=row.metadata?.icon||"•";return `<label class="resource-field"><span>${escapeHtml(icon)} ${escapeHtml(row.label_hu)}</span><input type="number" min="0" max="${Number(row.max_amount)||1000000}" value="0" inputmode="numeric" data-resource-prefix="${prefix}" data-resource-id="${escapeHtml(row.id)}" ${profile?'data-profile-resource':''}></label>`}
  function renderResourceBuilder(containerId,prefix,profile=false){const root=$(containerId);if(!root)return;const groups=groupCatalog();root.innerHTML=[...groups.entries()].map(([category,rows])=>`<section class="resource-group"><h4>${escapeHtml(CATEGORY_LABELS[category]||category)}</h4><div class="resource-grid">${rows.map(row=>resourceInput(row,prefix,profile)).join("")}</div></section>`).join("")||`<p class="empty">Nincs aktív katalóguselem.</p>`;qa("input",root).forEach(input=>input.addEventListener("input",()=>{if(prefix==="mail")updateMailPreview();if(profile)updateProfileDiff()}))}
  function renderAllResourceBuilders(){renderResourceBuilder("mailResourceFields","mail");renderResourceBuilder("redeemResourceFields","redeem");renderResourceBuilder("profileResourceFields","profile",true)}
  function rewardFrom(prefix){const resources={};qa(`[data-resource-prefix="${prefix}"]`).forEach(input=>{const amount=Number(input.value||0);if(Number.isInteger(amount)&&amount>0)resources[input.dataset.resourceId]=amount});const skins=listFromText($(prefix+"Skins")?.value||"");const reward={};if(Object.keys(resources).length)reward.resources=resources;if(skins.length)reward.skins=skins;return reward}
  function catalogMap(){return new Map(state.catalog.map(row=>[row.id,row]))}
  function rewardText(reward){const parts=[];const map=catalogMap();if(reward?.resources&&typeof reward.resources==="object")for(const [id,amount] of Object.entries(reward.resources)){const row=map.get(id);parts.push(`${row?.metadata?.icon||"•"} ${amount} ${row?.label_hu||id}`)}if(reward?.coins)parts.push(`🪙 ${reward.coins} Coin`);if(reward?.keys)parts.push(`🗝️ ${reward.keys} Common Key`);if(Array.isArray(reward?.skins)&&reward.skins.length)parts.push(`🐰 ${reward.skins.length} skin`);return parts.join(" · ")||"Nincs melléklet"}
  function getPath(object,path){let value=object;for(const key of path||[]){if(!value||typeof value!=="object")return 0;value=value[key]}const n=Number(value);return Number.isFinite(n)&&n>=0?Math.floor(n):0}

  async function searchPlayers(query,container,onSelect){container.innerHTML=`<p class="empty">Keresés…</p>`;try{const data=await api("search_players",{query});const players=data.players||[];if(!players.length){container.innerHTML=`<p class="empty">Nincs találat.</p>`;return}container.innerHTML=players.map((p,i)=>`<button type="button" class="search-result" data-player-index="${i}">${avatarMarkup(p)}<span><b>${escapeHtml(accountLabel(p))}</b><small>${escapeHtml(p.username||p.discordId||p.id)}</small><small>${p.coins||0} Coin · ${p.blossomGems||0} Gem</small></span></button>`).join("");qa("[data-player-index]",container).forEach(b=>b.addEventListener("click",()=>onSelect(players[Number(b.dataset.playerIndex)])))}catch(error){container.innerHTML=`<p class="empty">A keresés sikertelen.</p>`;toast(error.message,true)}}

  function selectMailPlayer(player){state.mailTarget=player;const box=$("mailSelectedPlayer");box.classList.remove("hidden");box.innerHTML=`<span><b>${escapeHtml(accountLabel(player))}</b><small>${escapeHtml(player.id)}</small></span><button type="button" id="clearMailPlayer">Törlés</button>`;$("mailPlayerResults").innerHTML="";$("clearMailPlayer").onclick=()=>{state.mailTarget=null;box.classList.add("hidden");box.innerHTML="";updateMailPreview()};updateMailPreview()}
  function mailAudienceLabel(audience){return audience==="existing"?"A jelenleg regisztrált fiókok":audience==="all_future"?"Minden jelenlegi és jövőbeli fiók":"Egy játékos"}
  function updateMailAudience(){const audience=document.querySelector('input[name="mailAudience"]:checked')?.value||"user";$("mailTargetBox").classList.toggle("hidden",audience!=="user");$("broadcastConfirm").classList.toggle("hidden",audience==="user");$("broadcastConfirmText").textContent=audience==="existing"?"Tudomásul veszem, hogy csak a most már regisztrált fiókok kapják meg.":"Tudomásul veszem, hogy az aktív időszakban később regisztrálók is megkapják.";updateMailPreview()}
  function updateMailPreview(){const audience=document.querySelector('input[name="mailAudience"]:checked')?.value||"user";$("mailPreviewAudience").textContent=audience==="user"?(state.mailTarget?accountLabel(state.mailTarget):"Egy játékos"):mailAudienceLabel(audience);$("mailPreviewTitle").textContent=$("mailTitleHu").value.trim()||"A levél címe";$("mailPreviewBody").textContent=$("mailBodyHu").value.trim()||"Itt jelenik meg a levél szövege.";$("mailPreviewReward").textContent=rewardText(rewardFrom("mail"))}
  async function submitMail(event){event.preventDefault();const audience=document.querySelector('input[name="mailAudience"]:checked')?.value||"user";if(audience==="user"&&!state.mailTarget)return toast("Válassz játékost.",true);if(audience!=="user"&&!$("broadcastConfirmCheck").checked)return toast("Erősítsd meg a globális levelet.",true);const button=$("mailSubmitBtn");setBusy(button,true,"Küldés…");try{await api("send_mail",{audience_type:audience,target_user_id:audience==="user"?state.mailTarget.id:null,title_hu:$("mailTitleHu").value,title_en:$("mailTitleEn").value,body_hu:$("mailBodyHu").value,body_en:$("mailBodyEn").value,attachments:rewardFrom("mail"),starts_at:localDateToIso("mailStartsAt"),expires_at:localDateToIso("mailExpiresAt")});toast("Levél elküldve.");event.target.reset();state.mailTarget=null;$("mailSelectedPlayer").classList.add("hidden");renderResourceBuilder("mailResourceFields","mail");updateMailAudience();refreshMailHistory()}catch(error){toast(`Küldési hiba: ${error.message}`,true)}finally{setBusy(button,false)}}
  async function refreshMailHistory(){const root=$("mailHistory");if(!root||$("gmApp").classList.contains("hidden"))return;root.innerHTML=`<p class="empty">Betöltés…</p>`;try{const data=await api("recent_mail");root.innerHTML=(data.messages||[]).map(m=>`<article class="activity-item"><header><b>${escapeHtml(m.title_hu)}</b><small>${formatDate(m.created_at)}</small></header><p>${m.audience_type==="user"?escapeHtml(m.target_user_id||""):mailAudienceLabel(m.audience_type)} · ${escapeHtml(rewardText(m.attachments))}</p></article>`).join("")||`<p class="empty">Még nincs levél.</p>`}catch(_){root.innerHTML=`<p class="empty">Nem sikerült betölteni.</p>`}}

  async function submitRedeem(event){event.preventDefault();const code=$("redeemCustomCode").value.trim();const reward=rewardFrom("redeem");if(!Object.keys(reward).length)return toast("Adj meg legalább egy jutalmat.",true);const max=Number($("redeemMax").value);const per=Number($("redeemPerUser").value);if(!Number.isInteger(max)||max<0||!Number.isInteger(per)||per<0)return toast("A limitek nem lehetnek negatívak.",true);if(max>0&&per>max)return toast("A játékosonkénti limit nem lehet nagyobb a globális limitnél.",true);const warning=per===0?"Ugyanaz a játékos is korlátlanul beválthatja!":max===0?"A kupon globálisan korlátlan lesz.":"";if(warning&&!confirm(`${warning}\n\nBiztosan létrehozod?`))return;const button=$("redeemSubmitBtn");setBusy(button,true,"Létrehozás…");try{const data=await api("create_redeem",{code,rewards:reward,max_redemptions:max,per_user_limit:per,starts_at:localDateToIso("redeemStartsAt"),expires_at:localDateToIso("redeemExpiresAt")});$("redeemCodeValue").textContent=data.code||code;$("redeemResult").classList.remove("hidden");toast("Kupon létrehozva.");refreshRedeemHistory()}catch(error){const msg=String(error.message).includes("redeem_code_already_exists")?"Ez a kuponkód már létezik.":error.message;toast(`Kuponhiba: ${msg}`,true)}finally{setBusy(button,false)}}
  async function refreshRedeemHistory(){const root=$("redeemHistory");if(!root||$("gmApp").classList.contains("hidden"))return;root.innerHTML=`<p class="empty">Betöltés…</p>`;try{const data=await api("recent_redeems");root.innerHTML=(data.codes||[]).map(c=>{const global=c.max_redemptions===0?"∞":c.max_redemptions;const per=c.per_user_limit===0?"∞":c.per_user_limit;return `<article class="activity-item"><header><b>${escapeHtml(c.code_prefix)}</b><small>${formatDate(c.created_at)}</small></header><p>${c.total_redemptions}/${global} beváltás · játékosonként ${per} · ${escapeHtml(rewardText(c.rewards))}</p></article>`}).join("")||`<p class="empty">Még nincs kupon.</p>`}catch(_){root.innerHTML=`<p class="empty">Nem sikerült betölteni.</p>`}}

  function selectProfilePlayer(player){state.profileTarget=player;$("profileSearchResults").innerHTML="";loadProfile(player.id)}
  function stringifyPretty(value,fallback){try{return JSON.stringify(value??fallback,null,2)}catch{return JSON.stringify(fallback,null,2)}}
  function fillProfileResources(save){state.profileResourceOriginal={};qa("[data-profile-resource]").forEach(input=>{const row=state.catalog.find(x=>x.id===input.dataset.resourceId);const value=getPath(save,row?.save_path||[]);input.value=value;state.profileResourceOriginal[input.dataset.resourceId]=value})}
  function fillProfileGmTitles(save){const owned=Array.isArray(save?.ownedTitles)?save.ownedTitles:[];state.profileGmTitlesOriginal=GM_TITLE_IDS.filter(id=>owned.includes(id));qa("[data-gm-title]").forEach(input=>{input.checked=state.profileGmTitlesOriginal.includes(input.dataset.gmTitle)})}
  function changedGmTitles(){const current=qa("[data-gm-title]:checked").map(input=>input.dataset.gmTitle).filter(Boolean);return JSON.stringify(current)===JSON.stringify(state.profileGmTitlesOriginal)?null:current}
  async function loadProfile(userId){$("profileEmpty").classList.remove("hidden");$("profileEmpty").innerHTML=`<b>Profil betöltése…</b>`;$("profileWorkspace").classList.add("hidden");try{const data=await api("get_profile",{target_user_id:userId});const profile=data.profile;state.profileOriginal=profile;const account=profile.account,saveRow=profile.save,save=saveRow.save_data||{};$("profileEmpty").classList.add("hidden");$("profileWorkspace").classList.remove("hidden");$("profileName").textContent=accountLabel(account);$("profileIdentity").textContent=[account.username,account.discordId,account.id].filter(Boolean).join(" · ");$("profileSaveMeta").textContent=`${saveRow.save_version||"—"} · frissítve: ${formatDate(saveRow.updated_at)}`;const avatar=$("profileAvatar");if(account.avatar){avatar.src=account.avatar;avatar.hidden=false;$("profileAvatarFallback").hidden=true}else{avatar.hidden=true;$("profileAvatarFallback").hidden=false}fillProfileResources(save);fillProfileGmTitles(save);$("profileSelectedSkin").value=typeof save.selectedSkin==="string"?save.selectedSkin:"cherry_default";$("profileSelectedStage").value=typeof save.selectedStageId==="string"?save.selectedStageId:"world_1_1";$("profileUnlockedSkins").value=Array.isArray(save.unlockedSkins)?save.unlockedSkins.join("\n"):"";$("profileUnlockedStages").value=Array.isArray(save.unlockedStages)?save.unlockedStages.join("\n"):"";$("profileInventory").value=stringifyPretty(save.inventory,[]);$("profileEquipped").value=stringifyPretty(save.equipped,{});$("profileReason").value="";$("rawSaveJson").textContent=stringifyPretty(save,{});updateProfileDiff()}catch(error){$("profileEmpty").classList.remove("hidden");$("profileEmpty").innerHTML=`<b>Nem sikerült betölteni.</b><p>${escapeHtml(error.message)}</p>`;toast(error.message,true)}}
  function currentProfilePatch(){const inventory=JSON.parse($("profileInventory").value||"[]"),equipped=JSON.parse($("profileEquipped").value||"{}");if(!Array.isArray(inventory))throw new Error("Az Inventory JSON tömb legyen.");if(!equipped||typeof equipped!=="object"||Array.isArray(equipped))throw new Error("Az Equipped JSON objektum legyen.");return{selectedSkin:$("profileSelectedSkin").value.trim(),selectedStageId:$("profileSelectedStage").value.trim(),unlockedSkins:listFromText($("profileUnlockedSkins").value),unlockedStages:listFromText($("profileUnlockedStages").value),inventory,equipped}}
  function changedPatch(){if(!state.profileOriginal)return{};const original=state.profileOriginal.save.save_data||{},current=currentProfilePatch(),patch={};for(const [key,value] of Object.entries(current)){const before=key in original?original[key]:key==="inventory"?[]:key==="equipped"?{}:key.startsWith("unlocked")?[]:undefined;if(JSON.stringify(before)!==JSON.stringify(value))patch[key]=value}return patch}
  function changedResources(){const values={};qa("[data-profile-resource]").forEach(input=>{const id=input.dataset.resourceId,value=Number(input.value||0);if(Number.isInteger(value)&&value>=0&&value!==state.profileResourceOriginal[id])values[id]=value});return values}
  function updateProfileDiff(){if(!state.profileOriginal||$("profileWorkspace").classList.contains("hidden"))return;const box=$("profileDiff");try{const p=Object.keys(changedPatch()),r=Object.keys(changedResources()),titles=changedGmTitles();const items=[...p,...r,...(titles===null?[]:["GM Title-ok"])];box.classList.toggle("changed",items.length>0);box.textContent=items.length?`Módosul: ${items.join(", ")}`:"Még nincs módosítás."}catch(error){box.classList.add("changed");box.textContent=`JSON hiba: ${error.message}`}}
  async function submitProfile(event){event.preventDefault();if(!state.profileTarget)return toast("Nincs kiválasztott játékos.",true);let patch,resources,gmTitles;try{patch=changedPatch();resources=changedResources();gmTitles=changedGmTitles()}catch(error){return toast(error.message,true)}if(!Object.keys(patch).length&&!Object.keys(resources).length&&gmTitles===null)return toast("Nincs mentendő módosítás.",true);const reason=$("profileReason").value.trim();if(reason.length<3)return toast("Írd le a módosítás indokát.",true);if(!confirm(`Biztosan módosítod ${accountLabel(state.profileTarget)} profilját?\n\nMinden szerverművelet előtt snapshot készül.`))return;const button=$("profileSaveBtn");setBusy(button,true,"Snapshot + mentés…");try{const snapshots=[];if(Object.keys(resources).length){const data=await api("update_profile_resources",{target_user_id:state.profileTarget.id,values:resources,reason});if(data.result?.snapshot_id)snapshots.push(data.result.snapshot_id)}if(Object.keys(patch).length){const data=await api("update_profile",{target_user_id:state.profileTarget.id,patch,reason});if(data.result?.snapshot_id)snapshots.push(data.result.snapshot_id)}if(gmTitles!==null){const data=await api("set_gm_titles",{target_user_id:state.profileTarget.id,titles:gmTitles,reason});if(data.result?.snapshot_id)snapshots.push(data.result.snapshot_id)}toast(`Profil mentve. Snapshot: ${snapshots.join(", ")||"elkészült"}`);await loadProfile(state.profileTarget.id);refreshActivity()}catch(error){toast(`Mentési hiba: ${error.message}`,true)}finally{setBusy(button,false)}}
  async function refreshActivity(){const root=$("auditHistory");if(!root||$("gmApp").classList.contains("hidden"))return;root.innerHTML=`<p class="empty">Betöltés…</p>`;try{const data=await api("recent_activity");root.innerHTML=(data.activity||[]).map(r=>`<article class="activity-item"><header><b>${escapeHtml(r.action)}</b><small>${formatDate(r.created_at)}</small></header><p>${escapeHtml(r.status)}${r.target_user_id?` · ${escapeHtml(r.target_user_id)}`:""}${r.error_code?` · ${escapeHtml(r.error_code)}`:""}</p></article>`).join("")||`<p class="empty">Még nincs naplózott művelet.</p>`}catch(_){root.innerHTML=`<p class="empty">A napló nem érhető el.</p>`}}

  function bindEvents(){$("discordLoginBtn").onclick=login;$("logoutBtn").onclick=logout;$("copyUserIdBtn").onclick=()=>copyText($("unauthorizedUserId").textContent);$("accountBtn").onclick=()=>$("accountSheet").classList.toggle("hidden");document.addEventListener("click",e=>{if(!e.target.closest("#accountBtn,#accountSheet"))$("accountSheet").classList.add("hidden")});qa("[data-module]").forEach(b=>b.onclick=()=>activateModule(b.dataset.module));qa('input[name="mailAudience"]').forEach(i=>i.onchange=updateMailAudience);$("mailSearchBtn").onclick=()=>searchPlayers($("mailPlayerSearch").value,$("mailPlayerResults"),selectMailPlayer);$("mailPlayerSearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();$("mailSearchBtn").click()}};qa("#mailForm input,#mailForm textarea").forEach(f=>f.addEventListener("input",updateMailPreview));$("mailForm").onsubmit=submitMail;$("refreshMailHistory").onclick=refreshMailHistory;$("redeemForm").onsubmit=submitRedeem;$("copyRedeemBtn").onclick=()=>copyText($("redeemCodeValue").textContent);$("refreshRedeemHistory").onclick=refreshRedeemHistory;$("profileSearchBtn").onclick=()=>searchPlayers($("profileSearch").value,$("profileSearchResults"),selectProfilePlayer);$("profileSearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();$("profileSearchBtn").click()}};qa("#profileForm input,#profileForm textarea").forEach(f=>f.addEventListener("input",updateProfileDiff));$("profileForm").onsubmit=submitProfile;$("refreshActivity").onclick=refreshActivity}
  async function start(){bindEvents();updateMailAudience();updateMailPreview();if(typeof factory!=="function"||!CONFIG.url||!CONFIG.publishableKey){showAuthStatus("A Supabase kliens konfigurációja hiányzik.");$("discordLoginBtn").disabled=true;return}state.client=factory(CONFIG.url,CONFIG.publishableKey,{auth:{storageKey:CONFIG.authStorageKey||"cherrift-supabase-auth-v063",persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:"pkce"}});state.client.auth.onAuthStateChange((_event,session)=>{state.session=session});try{await resolveSession()}catch(error){showAuthStatus(`Belépési hiba: ${error.message}`);toast(error.message,true)}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
