(() => {
  "use strict";
  if (window.__CHERRIFT_ECONOMY_V11__) return;
  window.__CHERRIFT_ECONOMY_V11__ = Object.freeze({ version:"1.1.0" });

  const TIERS = ["common","rare","epic","legendary"];
  const DEF = {
    common:{name:"Common Chest",icon:"📦",pity:10,asset:"assets/items/chests/common_chest.png",rarity:"Common"},
    rare:{name:"Rare Chest",icon:"🧰",pity:15,asset:"assets/items/chests/rare_chest.png",rarity:"Rare"},
    epic:{name:"Epic Chest",icon:"🎁",pity:25,asset:"assets/items/chests/epic_chest.png",rarity:"Epic"},
    legendary:{name:"Legendary Chest",icon:"🏆",pity:20,asset:"",rarity:"Legendary"},
  };
  const id=(name)=>document.getElementById(name);
  const q=(selector,root=document)=>root?.querySelector?.(selector)||null;
  const qa=(selector,root=document)=>Array.from(root?.querySelectorAll?.(selector)||[]);
  const n=(value)=>Math.max(0,Math.floor(Number(value)||0));

  function normalize(save){
    if(!save||typeof save!=="object")save={};
    save.coins=n(save.coins);save.keys=n(save.keys);save.blossomGems=n(save.blossomGems);save.sakuraEssence=n(save.sakuraEssence);
    save.resourceWallet=save.resourceWallet&&typeof save.resourceWallet==="object"?save.resourceWallet:{};
    save.resourceWallet.keys=save.resourceWallet.keys&&typeof save.resourceWallet.keys==="object"?save.resourceWallet.keys:{};
    for(const tier of ["rare","epic","legendary"])save.resourceWallet.keys[tier]=n(save.resourceWallet.keys[tier]);
    save.chests=save.chests&&typeof save.chests==="object"?save.chests:{};for(const tier of TIERS)save.chests[tier]=n(save.chests[tier]);
    save.gacha=save.gacha&&typeof save.gacha==="object"?save.gacha:{};save.gacha.pity=save.gacha.pity&&typeof save.gacha.pity==="object"?save.gacha.pity:{};for(const tier of TIERS)save.gacha.pity[tier]=n(save.gacha.pity[tier]);
    save.gacha.history=Array.isArray(save.gacha.history)?save.gacha.history.slice(0,50):[];
    save.bag=save.bag&&typeof save.bag==="object"?save.bag:{};save.bag.items=save.bag.items&&typeof save.bag.items==="object"?save.bag.items:{};
    save.arsenal=save.arsenal&&typeof save.arsenal==="object"?save.arsenal:{};save.arsenal.materials=save.arsenal.materials&&typeof save.arsenal.materials==="object"?save.arsenal.materials:{};
    save.economy=save.economy&&typeof save.economy==="object"?save.economy:{};save.economy.totalChestOpens=n(save.economy.totalChestOpens);
    save.inventory=Array.isArray(save.inventory)?save.inventory:[];save.unlockedSkins=Array.isArray(save.unlockedSkins)?save.unlockedSkins:[];
    return save;
  }
  function keyCount(save,tier){save=normalize(save);return tier==="common"?save.keys:n(save.resourceWallet.keys[tier])}
  function chestCount(save,tier){return normalize(save).chests[tier]}
  function canOpen(save,tier){return chestCount(save,tier)>0||keyCount(save,tier)>0}
  function consume(save,tier){save=normalize(save);if(save.chests[tier]>0){save.chests[tier]--;return"chest"}if(tier==="common"&&save.keys>0){save.keys--;return"key"}if(tier!=="common"&&save.resourceWallet.keys[tier]>0){save.resourceWallet.keys[tier]--;return"key"}return null}
  function currentWorld(save){return Math.max(1,...Object.keys(save.clearedStages||{}).map(key=>Number(key.match(/world_(\d+)/)?.[1])||1))}
  function randomSkin(rarity){const pool=(window.CHERRIFT_DATA?.skins||[]).filter(s=>String(s.rarity).toLowerCase()===rarity.toLowerCase());return pool.length?pool[Math.floor(Math.random()*pool.length)]:null}
  function grantSkin(save,rarity){const skin=randomSkin(rarity);if(!skin){const amount={Common:5,Rare:15,Epic:40,Legendary:100}[rarity]||5;save.sakuraEssence+=amount;return{kind:"essence",rarity,amount,label:`${amount} Sakura Essence`,icon:"🌸"}}if(save.unlockedSkins.includes(skin.id)){const amount={Common:5,Rare:15,Epic:40,Legendary:100}[rarity]||5;save.sakuraEssence+=amount;return{kind:"duplicateSkin",rarity,amount,label:`${skin.name} duplicate → ${amount} Essence`,icon:skin.icon||skin.emoji||"🐰"}}save.unlockedSkins.push(skin.id);return{kind:"skin",rarity,skinId:skin.id,label:skin.name,icon:skin.icon||skin.emoji||"🐰"}}
  function grantGear(save,rarity){const create=window.CHERRIFT_V050?.createGear;if(typeof create!=="function"){const coins={Common:30,Rare:90,Epic:240,Legendary:650}[rarity]||30;save.coins+=coins;return{kind:"coins",rarity,amount:coins,label:`${coins} Coin`,icon:"🪙"}}const item=create(currentWorld(save),rarity);window.CHERRIFT_V070?.syncItemToArsenal?.(item,save);if(save.inventory.length>=80){const coins=window.CHERRIFT_V050?.sellValue?.(item)||{Common:20,Rare:60,Epic:180,Legendary:500}[rarity]||20;save.coins+=coins;return{kind:"coins",rarity,amount:coins,label:`Inventory full → ${coins} Coin`,icon:"🪙"}}save.inventory.push(item);save.lootStats||={};save.lootStats.totalDrops=n(save.lootStats.totalDrops)+1;const key=`${rarity.toLowerCase()}Drops`;save.lootStats[key]=n(save.lootStats[key])+1;return{kind:"gear",rarity,item,label:`${rarity} ${item.type||""} ${item.slot||"Gear"}`.trim(),icon:window.UI?.gearEmoji?.(item)||"⚔️"}}
  function roll(save,tier){const pity=++save.gacha.pity[tier],guarantee=pity%DEF[tier].pity===0,r=Math.random();if(tier==="common"){if(guarantee)return grantSkin(save,"Common");if(r<.86)return grantGear(save,"Common");if(r<.97)return grantSkin(save,"Common");if(r<.995)return grantGear(save,"Rare");return grantSkin(save,"Rare")}if(tier==="rare"){if(guarantee)return grantSkin(save,"Rare");if(r<.35)return grantGear(save,"Common");if(r<.82)return grantGear(save,"Rare");if(r<.91)return grantSkin(save,"Common");if(r<.985)return grantSkin(save,"Rare");return grantGear(save,"Epic")}if(tier==="epic"){if(guarantee)return r<.82?grantGear(save,"Epic"):grantSkin(save,"Epic");if(r<.46)return grantGear(save,"Rare");if(r<.78)return grantGear(save,"Epic");if(r<.89)return grantSkin(save,"Rare");if(r<.985)return grantSkin(save,"Epic");return grantGear(save,"Legendary")}if(guarantee)return r<.72?grantGear(save,"Legendary"):grantSkin(save,"Legendary");if(r<.30)return grantGear(save,"Epic");if(r<.75)return grantGear(save,"Legendary");if(r<.88)return grantSkin(save,"Epic");return grantSkin(save,"Legendary")}
  function saveProgress(save){normalize(save);try{window.CherriftStorage?.save?.(save)}catch(_){}window.UI?.refreshMenu?.();render()}
  function openChest(tier){if(!TIERS.includes(tier)||!window.UI?.save)return null;const save=normalize(UI.save);if(!consume(save,tier)){UI.toast?.(`Nincs ${DEF[tier].name} vagy hozzá való kulcs.`);return null}const reward=roll(save,tier);save.economy.totalChestOpens++;save.gacha.history.unshift({type:tier,reward:{kind:reward.kind,rarity:reward.rarity,label:reward.label,amount:reward.amount||0},at:Date.now()});save.gacha.history=save.gacha.history.slice(0,50);saveProgress(save);UI.toast?.(`Megszerezve: ${reward.label}`);showReward(reward,tier);return reward}
  function showReward(reward,tier){const result=id("economyV11Result");if(result){result.classList.remove("hidden");result.innerHTML=`<span>${reward.icon||DEF[tier].icon}</span><div><small>${DEF[tier].name}</small><b>${escapeHtml(reward.label)}</b><em>${reward.rarity||""}</em></div>`}const assets=window.CHERRIFT_ITEM_ASSETS;window.CHERRIFT_REWARDS?.show?.([{key:`economy:${tier}:${Date.now()}`,name:reward.label,amount:reward.amount||1,asset:reward.item?.asset||assets?.chests?.[tier],rarity:reward.rarity||DEF[tier].rarity,kind:reward.kind}])}
  function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
  function tierCard(save,tier){const def=DEF[tier],asset=def.asset?`<img src="${def.asset}" alt="">`:`<span class="legendary-chest">🏆</span>`;return `<article class="economy-card-v11 ${tier}">${asset}<div><h3>${def.name}</h3><p>Chest: <b>${chestCount(save,tier)}</b> · Key: <b>${keyCount(save,tier)}</b></p><small>Pity: ${save.gacha.pity[tier]%def.pity}/${def.pity}</small></div><button data-economy-open="${tier}" ${canOpen(save,tier)?"":"disabled"}>NYITÁS</button></article>`}
  function ensureStyles(){if(id("economyV11Css"))return;const style=document.createElement("style");style.id="economyV11Css";style.textContent=`#economyV11{overflow:auto;padding-bottom:90px}.economy-shell-v11{max-width:1050px;margin:auto;padding:18px}.economy-head-v11{display:flex;justify-content:space-between;gap:12px;align-items:center}.economy-head-v11 h2{margin:0}.economy-currencies-v11{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.economy-currencies-v11 b{padding:9px 12px;border:1px solid rgba(255,255,255,.14);border-radius:999px;background:rgba(255,255,255,.05)}.economy-grid-v11{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.economy-card-v11{display:grid;grid-template-columns:82px 1fr auto;align-items:center;gap:12px;padding:15px;border:1px solid rgba(255,255,255,.12);border-radius:18px;background:rgba(26,13,29,.86)}.economy-card-v11 img,.legendary-chest{width:76px;height:76px;object-fit:contain;display:grid;place-items:center;font-size:52px}.economy-card-v11 h3{margin:0 0 5px}.economy-card-v11 p{margin:0 0 4px}.economy-card-v11 small{opacity:.7}.economy-card-v11 button{min-height:44px;padding:0 14px;border:0;border-radius:12px;color:#fff;font-weight:900;background:linear-gradient(120deg,#bd2870,#f067aa)}.economy-card-v11 button:disabled{opacity:.35}.economy-card-v11.rare{box-shadow:inset 0 0 0 1px rgba(77,163,255,.16)}.economy-card-v11.epic{box-shadow:inset 0 0 0 1px rgba(184,89,255,.18)}.economy-card-v11.legendary{box-shadow:inset 0 0 0 1px rgba(255,203,60,.24)}.economy-result-v11{display:flex;gap:13px;align-items:center;margin-top:14px;padding:16px;border:1px solid rgba(255,216,118,.24);border-radius:17px;background:rgba(255,195,54,.08)}.economy-result-v11>span{font-size:38px}.economy-result-v11 b,.economy-result-v11 small,.economy-result-v11 em{display:block}.economy-result-v11 em{color:#ffd36c}.economy-nav-v11{position:fixed;right:14px;bottom:90px;z-index:22;width:54px;height:54px;border:0;border-radius:50%;background:linear-gradient(135deg,#d52f7d,#7d46cf);color:#fff;font-size:24px;box-shadow:0 10px 35px #0008}@media(max-width:720px){.economy-grid-v11{grid-template-columns:1fr}.economy-card-v11{grid-template-columns:65px 1fr}.economy-card-v11 button{grid-column:1/-1}.economy-card-v11 img,.legendary-chest{width:60px;height:60px;font-size:42px}}`;document.head.appendChild(style)}
  function ensurePanel(){if(id("economyV11"))return;const app=id("app");if(!app)return;app.insertAdjacentHTML("beforeend",`<section id="economyV11" class="panel hidden"><div class="economy-shell-v11"><header class="economy-head-v11"><div><small>CHERRIFT ECONOMY v1.1</small><h2>Chest Vault</h2><p>Külön tier kulcsok és ládák.</p></div><button class="back" data-economy-back>←</button></header><div id="economyV11Currencies" class="economy-currencies-v11"></div><div id="economyV11Grid" class="economy-grid-v11"></div><div id="economyV11Result" class="economy-result-v11 hidden"></div></div></section>`);const floating=document.createElement("button");floating.id="economyV11Floating";floating.className="economy-nav-v11";floating.type="button";floating.title="Chest Vault";floating.textContent="🏆";document.body.appendChild(floating);floating.onclick=openPanel;id("economyV11").addEventListener("click",event=>{const open=event.target.closest("[data-economy-open]");if(open)openChest(open.dataset.economyOpen);if(event.target.closest("[data-economy-back]"))window.UI?.open?.("menu")});const nav=q(".menu-left .main-nav");if(nav&&!id("economyV11DesktopBtn")){const b=document.createElement("button");b.id="economyV11DesktopBtn";b.className="menu-btn";b.type="button";b.innerHTML="<span>🏆</span><i>CHEST VAULT</i><b>›</b>";b.onclick=openPanel;nav.appendChild(b)}}
  function render(){if(!id("economyV11")||!window.UI?.save)return;const save=normalize(UI.save);id("economyV11Currencies").innerHTML=`<b>🪙 ${save.coins} Coin</b><b>💎 ${save.blossomGems} Blossom Gem</b><b>🌸 ${save.sakuraEssence} Essence</b>`;id("economyV11Grid").innerHTML=TIERS.map(t=>tierCard(save,t)).join("")}
  function openPanel(){ensurePanel();render();const custom="economyV11";qa("#app > section.panel").forEach(panel=>panel.classList.toggle("hidden",panel.id!==custom));document.body.classList.remove("is-playing");scrollTo({top:0,behavior:"smooth"})}
  function patchOpen(){if(!window.UI||UI.__economyV11OpenPatched)return;const previous=UI.open?.bind(UI);if(previous)UI.open=function(panel,...args){if(panel==="economyV11"){openPanel();return}return previous(panel,...args)};UI.__economyV11OpenPatched=true}
  function patchStorage(){if(!window.CherriftStorage||CherriftStorage.__economyV11)return;const d=CherriftStorage.defaults.bind(CherriftStorage),l=CherriftStorage.load.bind(CherriftStorage),s=CherriftStorage.save.bind(CherriftStorage);CherriftStorage.defaults=()=>normalize(d());CherriftStorage.load=()=>normalize(l());CherriftStorage.save=save=>s(normalize(save));CherriftStorage.__economyV11=true}
  function patchRefresh(){if(!window.UI||UI.__economyV11Refresh)return;const previous=UI.refreshMenu?.bind(UI);if(previous)UI.refreshMenu=function(...args){const out=previous(...args);if(this.save)normalize(this.save);render();return out};UI.__economyV11Refresh=true}
  function start(){if(!window.UI||!window.CherriftStorage||!window.CHERRIFT_DATA){setTimeout(start,120);return}ensureStyles();patchStorage();patchOpen();patchRefresh();if(UI.save)normalize(UI.save);ensurePanel();render();console.info("[CHERRIFT] Economy v1.1 tiered keys/chests loaded.")}
  window.CHERRIFT_ECONOMY_V11={version:"1.1.0",normalize,keyCount,chestCount,canOpen,openChest,open:openPanel,render};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
